### Preprocess the raw data from NOAA
This notebook is setup to take in the CSV from NOAA and remove the unneccasary data. This will also seperate out each station for later positioning.

In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

In [2]:
#Getting a list of files in raw data folder
filenames = os.listdir('D:/Nico/Desktop/full_grid')

In [3]:
header_wanted = [
 'HOURLYVISIBILITY',
 'HOURLYDRYBULBTEMPC',
 'HOURLYWETBULBTEMPC',
 'HOURLYDewPointTempC',
 'HOURLYRelativeHumidity',
 'HOURLYWindSpeed',
 'HOURLYWindGustSpeed',
 'HOURLYStationPressure',
 'HOURLYPressureTendency',
 'HOURLYPressureChange',
 'HOURLYSeaLevelPressure',
 'HOURLYPrecip',
 'HOURLYAltimeterSetting']

In [4]:
usecols = ['DATE','STATION'] + header_wanted

In [5]:
#Loading all files into a pandas Dataframe
tqdm.pandas()
df = pd.concat([pd.read_csv('D:/Nico/Desktop/full_grid/{}'.format(x), usecols=usecols, low_memory=False) for x in tqdm(filenames)])

100%|██████████████████████████████████████████████████████████████████████████████████| 82/82 [03:04<00:00,  2.25s/it]

In [6]:
#Getting the station names
wban = df['STATION'].unique()

In [7]:
def remove_letters(headers,dataframes):
    for i in tqdm(headers):
        dataframes[i].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
        dataframes[i] = dataframes[i].apply(pd.to_numeric)

In [8]:
remove_letters(header_wanted,df)

100%|███████████████████████████████████████████████████████████████████████████████| 13/13 [1:16:01<00:00, 350.87s/it]

In [17]:
by_station_list = []

for i in tqdm(wban):
    by_station_list.append(df.loc[df.STATION == i])
del df

100%|████████████████████████████████████████████████████████████████████████████████| 394/394 [10:28<00:00,  1.60s/it]

In [18]:
by_station_list[0].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50881 entries, 0 to 50880
Data columns (total 15 columns):
STATION                   50881 non-null object
DATE                      50881 non-null object
HOURLYVISIBILITY          50315 non-null float64
HOURLYDRYBULBTEMPC        43475 non-null float64
HOURLYWETBULBTEMPC        41842 non-null float64
HOURLYDewPointTempC       43475 non-null float64
HOURLYRelativeHumidity    43475 non-null float64
HOURLYWindSpeed           50380 non-null float64
HOURLYWindGustSpeed       3039 non-null float64
HOURLYStationPressure     48624 non-null float64
HOURLYPressureTendency    0 non-null float64
HOURLYPressureChange      0 non-null float64
HOURLYSeaLevelPressure    0 non-null float64
HOURLYPrecip              0 non-null float64
HOURLYAltimeterSetting    48624 non-null float64
dtypes: float64(13), object(2)
memory usage: 6.2+ MB

In [22]:
for i in tqdm(range(len(by_station_list))):
    by_station_list[i] = by_station_list[i].set_index(pd.DatetimeIndex(by_station_list[i]['DATE']))

100%|████████████████████████████████████████████████████████████████████████████████| 394/394 [00:05<00:00, 68.16it/s]

In [23]:
by_station_list[0].info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 50881 entries, 2016-08-01 00:15:00 to 2018-07-31 23:59:00
Data columns (total 15 columns):
STATION                   50881 non-null object
DATE                      50881 non-null object
HOURLYVISIBILITY          50315 non-null float64
HOURLYDRYBULBTEMPC        43475 non-null float64
HOURLYWETBULBTEMPC        41842 non-null float64
HOURLYDewPointTempC       43475 non-null float64
HOURLYRelativeHumidity    43475 non-null float64
HOURLYWindSpeed           50380 non-null float64
HOURLYWindGustSpeed       3039 non-null float64
HOURLYStationPressure     48624 non-null float64
HOURLYPressureTendency    0 non-null float64
HOURLYPressureChange      0 non-null float64
HOURLYSeaLevelPressure    0 non-null float64
HOURLYPrecip              0 non-null float64
HOURLYAltimeterSetting    48624 non-null float64
dtypes: float64(13), object(2)
memory usage: 6.2+ MB

In [39]:
for i in tqdm(range(len(by_station_list))):
    by_station_list[i] = by_station_list[i].resample('60T').mean()

100%|████████████████████████████████████████████████████████████████████████████████| 394/394 [00:04<00:00, 80.90it/s]

In [45]:
wban_list = []
for x in wban:
    wban_list.append(x[:4] + x[5:])

In [46]:
wban_list[0]

'WBAN00445'

In [40]:
by_station_list[0]

,HOURLYVISIBILITY,HOURLYDRYBULBTEMPC,HOURLYWETBULBTEMPC,HOURLYDewPointTempC,HOURLYRelativeHumidity,HOURLYWindSpeed,HOURLYWindGustSpeed,HOURLYStationPressure,HOURLYPressureTendency,HOURLYPressureChange,HOURLYSeaLevelPressure,HOURLYPrecip,HOURLYAltimeterSetting
DATE,,,,,,,,,,,,,
2016-08-01 00:00:00,1000.000000,254.000000,25.600000,254.000000,100.000000,3.000000,NaN,2992.000000,NaN,NaN,NaN,NaN,3004.000000
2016-08-01 01:00:00,1000.000000,246.333333,24.600000,246.333333,100.000000,1.000000,NaN,2991.333333,NaN,NaN,NaN,NaN,3003.333333
2016-08-01 02:00:00,1000.000000,NaN,NaN,NaN,NaN,2.000000,NaN,2992.000000,NaN,NaN,NaN,NaN,3004.000000
2016-08-01 03:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2992.333333,NaN,NaN,NaN,NaN,3004.333333
2016-08-01 04:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2994.000000,NaN,NaN,NaN,NaN,3006.000000
2016-08-01 05:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2995.666667,NaN,NaN,NaN,NaN,3007.666667
2016-08-01 06:00:00,1000.000000,NaN,NaN,NaN,NaN,2.000000,NaN,2997.333333,NaN,NaN,NaN,NaN,3009.333333
2016-08-01 07:00:00,1000.000000,253.000000,24.600000,242.666667,94.333333,3.666667,NaN,2998.000000,NaN,NaN,NaN,NaN,3010.000000
2016-08-01 08:00:00,1000.000000,274.000000,24.933333,238.333333,81.000000,1.666667,NaN,2998.000000,NaN,NaN,NaN,NaN,3010.000000
2016-08-01 09:00:00,1000.000000,296.333333,25.066667,231.333333,68.000000,2.000000,NaN,2998.000000,NaN,NaN,NaN,NaN,3010.000000
2016-08-01 10:00:00,1000.000000,310.000000,25.366667,229.666667,62.333333,1.000000,NaN,2997.666667,NaN,NaN,NaN,NaN,3009.666667
2016-08-01 11:00:00,1000.000000,327.333333,25.233333,221.333333,54.000000,2.666667,NaN,2995.333333,NaN,NaN,NaN,NaN,3007.333333
2016-08-01 12:00:00,1000.000000,333.000000,25.000000,214.000000,50.000000,3.666667,NaN,2993.333333,NaN,NaN,NaN,NaN,3005.333333
2016-08-01 13:00:00,1000.000000,338.666667,25.033333,213.333333,48.000000,3.666667,NaN,2992.333333,NaN,NaN,NaN,NaN,3004.333333
2016-08-01 14:00:00,1000.000000,336.333333,25.333333,219.000000,50.333333,5.666667,NaN,2991.000000,NaN,NaN,NaN,NaN,3003.000000
2016-08-01 15:00:00,1000.000000,329.666667,25.066667,215.333333,51.333333,10.000000,NaN,2990.000000,NaN,NaN,NaN,NaN,3002.000000
2016-08-01 16:00:00,1000.000000,307.000000,24.566667,218.666667,59.333333,7.000000,NaN,2990.666667,NaN,NaN,NaN,NaN,3002.666667
2016-08-01 17:00:00,1000.000000,290.666667,24.200000,219.666667,65.666667,3.666667,NaN,2991.000000,NaN,NaN,NaN,NaN,3003.000000
2016-08-01 18:00:00,1000.000000,278.000000,23.966667,222.000000,71.666667,3.000000,NaN,2993.333333,NaN,NaN,NaN,NaN,3005.333333
2016-08-01 19:00:00,1000.000000,264.333333,23.633333,223.666667,78.666667,0.000000,NaN,2992.666667,NaN,NaN,NaN,NaN,3004.666667
2016-08-01 20:00:00,1000.000000,256.333333,23.933333,232.333333,86.666667,1.000000,NaN,2994.666667,NaN,NaN,NaN,NaN,3006.666667
2016-08-01 21:00:00,1000.000000,247.333333,24.600000,247.333333,100.000000,2.000000,NaN,2996.000000,NaN,NaN,NaN,NaN,3008.000000
2016-08-01 22:00:00,1000.000000,244.000000,24.400000,244.000000,100.000000,0.000000,NaN,2995.000000,NaN,NaN,NaN,NaN,3007.000000
2016-08-01 23:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2995.000000,NaN,NaN,NaN,NaN,3007.000000
2016-08-02 00:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2994.000000,NaN,NaN,NaN,NaN,3006.000000
2016-08-02 01:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2994.666667,NaN,NaN,NaN,NaN,3006.666667
2016-08-02 02:00:00,1000.000000,NaN,NaN,NaN,NaN,1.000000,NaN,2995.000000,NaN,NaN,NaN,NaN,3007.000000
2016-08-02 03:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2995.000000,NaN,NaN,NaN,NaN,3007.000000
2016-08-02 04:00:00,800.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2995.000000,NaN,NaN,NaN,NaN,3007.000000
2016-08-02 05:00:00,700.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2996.000000,NaN,NaN,NaN,NaN,3008.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-30 18:00:00,1000.000000,266.000000,22.000000,196.000000,65.333333,6.333333,24.0,2980.666667,NaN,NaN,NaN,NaN,2992.666667
2018-07-30 19:00:00,1000.000000,245.000000,21.400000,198.666667,75.333333,3.000000,NaN,2982.666667,NaN,NaN,NaN,NaN,2994.666667
2018-07-30 20:00:00,1000.000000,245.000000,21.900000,205.666667,78.333333,1.666667,NaN,2984.000000,NaN,NaN,NaN,NaN,2996.000000
2018-07-30 21:00:00,1000.000000,247.333333,22.266667,210.333333,79.666667,1.000000,NaN,2984.333333,NaN,NaN,NaN,NaN,2996.333333
2018-07-30 22:00:00,1000.000000,246.666667,22.266667,209.666667,79.666667,3.666667,NaN,2985.666667,NaN,NaN,NaN,NaN,2997.666667
2018-07-30 23:00:00,1000.000000,242.333333,22.133333,210.333333,82.333333,2.000000,NaN,2984.666667,NaN,NaN,NaN,NaN,2996.666667
2018-07-31 00:00:00,1000.000000,236.666667,21.933333,211.666667,85.666667,0.000000,NaN,2984.000000,NaN,NaN,NaN,NaN,2996.000000
2018-07-31 01:00:00,1000.000000,231.333333,21.833333,211.333333,88.333333,0.000000,NaN,2982.666667,NaN,NaN,NaN,NaN,2994.666667
2018-07-31 02:00:00,900.000000,227.000000,21.700000,211.666667,91.000000,3.333333,NaN,2982.000000,NaN,NaN,NaN,NaN,2994.000000
2018-07-31 03:00:00,700.000000,225.666667,21.566667,211.000000,91.666667,2.000000,NaN,2982.666667,NaN,NaN,NaN,NaN,2994.666667
2018-07-31 04:00:00,900.000000,224.666667,21.500000,210.666667,92.000000,1.000000,NaN,2984.666667,NaN,NaN,NaN,NaN,2996.666667
2018-07-31 05:00:00,633.333333,221.000000,21.233333,208.333333,92.666667,0.000000,NaN,2986.333333,NaN,NaN,NaN,NaN,2998.333333
2018-07-31 06:00:00,800.000000,229.333333,21.900000,214.000000,91.000000,1.666667,NaN,2986.666667,NaN,NaN,NaN,NaN,2998.666667
2018-07-31 07:00:00,1000.000000,248.333333,22.700000,217.666667,83.000000,3.666667,NaN,2987.000000,NaN,NaN,NaN,NaN,2999.000000
2018-07-31 08:00:00,1000.000000,272.666667,23.800000,223.666667,74.666667,4.000000,NaN,2987.000000,NaN,NaN,NaN,NaN,2999.000000
2018-07-31 09:00:00,1000.000000,297.666667,24.300000,219.000000,62.666667,5.666667,NaN,2986.333333,NaN,NaN,NaN,NaN,2998.333333
2018-07-31 10:00:00,900.000000,306.000000,24.233333,212.666667,57.666667,6.333333,NaN,2985.333333,NaN,NaN,NaN,NaN,2997.333333
2018-07-31 11:00:00,1000.000000,315.666667,24.100000,206.000000,52.333333,5.000000,NaN,2984.000000,NaN,NaN,NaN,NaN,2996.000000
2018-07-31 12:00:00,800.000000,313.666667,24.366667,211.666667,55.000000,5.000000,NaN,2980.666667,NaN,NaN,NaN,NaN,2992.666667
2018-07-31 13:00:00,900.000000,285.333333,24.100000,221.666667,68.666667,5.000000,NaN,2978.333333,NaN,NaN,NaN,NaN,2990.333333
2018-07-31 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-31 23:00:00,1000.000000,NaN,NaN,NaN,NaN,0.000000,NaN,2987.666667,NaN,NaN,NaN,NaN,2999.666667

In [47]:
for i in tqdm(range(len(wban))):
    by_station_list[i].to_csv('D:/Nico/Desktop/processed_data/{}.csv'.format(wban_list[i]))

100%|████████████████████████████████████████████████████████████████████████████████| 394/394 [02:04<00:00,  3.17it/s]

### Current Issues

1) data is not synced across time-zone and all entries start at midnight local time. 

2) some stations have multiple entries per hour and need to be reduced.

Solutions

Remove rows from data based on timezone to sync times
limit only 1 entry per hour for a station